version: "3.9"

services:
  app:
    environment:
      - TZ=Europe/Kyiv
    build: .
    container_name: autoria_app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - ./dumps:/app/dumps

  postgres:
    image: postgres:15
    container_name: autoria_postgres
    environment:
      POSTGRES_DB: autoria
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
       - TZ=Europe/Kyiv
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
